;
; Style variables for UI
; src\ui\config\constants.au3
;
#include-once


global const $STYLE_WIDTH = 420
global const $STYLE_HEIGHT = 246

global const $STYLE_GRP_LEFT = 4 ; GRP - group
global const $STYLE_GRP_TOP = $STYLE_GRP_LEFT + 4
global const $STYLE_GRP_WIDTH = $STYLE_WIDTH - ($STYLE_GRP_LEFT * 2)
global const $STYLE_GRP_PADDING = 6
global const $STYLE_GRP_PADDING_TOP = 12

global const $STYLE_GRP_GAME_MGW_LBL_LEFT = $STYLE_GRP_LEFT + $STYLE_GRP_PADDING ; MGW - main game window, LBL - label
global const $STYLE_GRP_GAME_MGW_LBL_TOP = $STYLE_GRP_TOP + $STYLE_GRP_PADDING + $STYLE_GRP_PADDING_TOP
global const $STYLE_GRP_GAME_MGW_LBL_HEIGHT = 14
global const $STYLE_GRP_GAME_MGW_INPT_TOP = $STYLE_GRP_GAME_MGW_LBL_TOP + $STYLE_GRP_GAME_MGW_LBL_HEIGHT + 2 ; INPT - input
global const $STYLE_GRP_GAME_MGW_B_BTN_WIDTH = 32; B - browse, BTN - button
global const $STYLE_GRP_GAME_MGW_INPT_WIDTH = $STYLE_GRP_WIDTH - ($STYLE_GRP_PADDING * 2) - $STYLE_GRP_GAME_MGW_B_BTN_WIDTH - 6
global const $STYLE_GRP_GAME_MGW_INPT_HEIGHT = 24
global const $STYLE_GRP_GAME_MGW_B_BTN_LEFT = $STYLE_GRP_GAME_MGW_LBL_LEFT + $STYLE_GRP_GAME_MGW_INPT_WIDTH + 6

global const $STYLE_GRP_GAME_OGW_LBL_TOP = $STYLE_GRP_GAME_MGW_INPT_TOP + $STYLE_GRP_GAME_MGW_INPT_HEIGHT + 10 ; OGW - other game window
global const $STYLE_GRP_GAME_OGW_INPT_TOP = $STYLE_GRP_GAME_OGW_LBL_TOP + $STYLE_GRP_GAME_MGW_LBL_HEIGHT + 2
global const $STYLE_GRP_GAME_HEIGHT = ($STYLE_GRP_GAME_MGW_LBL_HEIGHT * 2) + ($STYLE_GRP_GAME_MGW_INPT_HEIGHT * 2) + 41

global const $STYLE_GRP_START_TOP = $STYLE_GRP_TOP + $STYLE_GRP_GAME_HEIGHT + 4
global const $STYLE_GRP_START_M_CBOX_TOP = $STYLE_GRP_START_TOP + $STYLE_GRP_PADDING + $STYLE_GRP_PADDING_TOP ; M - main, CBOX - checkbox
global const $STYLE_GRP_START_M_CBOX_WIDTH = 44
global const $STYLE_GRP_START_RUN_BTN_LEFT = $STYLE_GRP_GAME_MGW_LBL_LEFT + $STYLE_GRP_START_M_CBOX_WIDTH + 6
global const $STYLE_GRP_START_RUN_BTN_WIDTH = $STYLE_GRP_WIDTH - ($STYLE_GRP_PADDING * 2) - $STYLE_GRP_START_M_CBOX_WIDTH - 6
global const $STYLE_GRP_START_HEIGHT = $STYLE_GRP_GAME_MGW_INPT_HEIGHT + 26

global const $STYLE_GRP_SOBO_TOP = $STYLE_GRP_START_TOP + $STYLE_GRP_START_HEIGHT + 4
global const $STYLE_GRP_SOBO_TANK_BTN_TOP = $STYLE_GRP_SOBO_TOP + $STYLE_GRP_PADDING + $STYLE_GRP_PADDING_TOP
local const $STYLE_GRP_SOBO_BTN_SPACE = 5
global const $STYLE_GRP_SOBO_BTN_WIDTH = ($STYLE_GRP_WIDTH - ($STYLE_GRP_PADDING * 2) - ($STYLE_GRP_SOBO_BTN_SPACE * 4)) / 5
global const $STYLE_GRP_SOBO_HEALER_BTN_LEFT = $STYLE_GRP_GAME_MGW_LBL_LEFT + $STYLE_GRP_SOBO_BTN_WIDTH + $STYLE_GRP_SOBO_BTN_SPACE
global const $STYLE_GRP_SOBO_DPS0_BTN_LEFT = $STYLE_GRP_SOBO_HEALER_BTN_LEFT + $STYLE_GRP_SOBO_BTN_WIDTH + $STYLE_GRP_SOBO_BTN_SPACE
global const $STYLE_GRP_SOBO_DPS1_BTN_LEFT = $STYLE_GRP_SOBO_DPS0_BTN_LEFT + $STYLE_GRP_SOBO_BTN_WIDTH + $STYLE_GRP_SOBO_BTN_SPACE
global const $STYLE_GRP_SOBO_DPS2_BTN_LEFT = $STYLE_GRP_SOBO_DPS1_BTN_LEFT + $STYLE_GRP_SOBO_BTN_WIDTH + $STYLE_GRP_SOBO_BTN_SPACE
